org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = false

authors = ["Ryderbelserion, Badbones69, JackStar6677"]
website  = https://github.com/DrakesCraft-Labs/CrazyAuctions
sources = https://github.com/DrakesCraft-Labs/CrazyAuctions
issues = https://github.com/DrakesCraft-Labs/CrazyAuctions/issues
